version: "3.8"
services:

    php-fpm:
      build: ./docker/php-fpm
      container_name: php-fpm
      working_dir: /application
      volumes:
        - ./app:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini